-- SQLBook: Code
CREATE TABLE Comment(
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    pseudo VARCHAR(255),
    text VARCHAR(10000)
) DEFAULT CHARSET UTF8;
-- SQLBook: Code
ALTER TABLE Comment
ADD COLUMN articleId int,
ADD FOREIGN KEY fk_article(articleId) REFERENCES Article(id) ON DELETE CASCADE;
